name: Spawn-Heal-System
author: LucaHD_YT
version: 1.3
main: de.lucahdyt.SpawnhealSystem.main.Main

commands:
  heal:
    description: Heile dich oder andere Spieler!
  setspawn:
    description: Setze den Spawn!
  Spawn:
    description: Teleportiere dich zum Spawn!
